FutureCode1601/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lib/', include('library.urls')),
    path('shop/', include('shop.urls')),
    path('basket/', include('basket.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HouseProject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('house_shop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from .views import *
from rest_framework import routers

urlpatterns = [
    path('product/all/', product_list, name='product_list'),
    path('product/one-filter/', get_one_filter_product, name='get_one_filter'),
    path('product/more-filter/', get_more_filter_product, name='get_more_filter'),
    path('product/all-filter/', product_catalog_with_filter, name='product_list_filter'),
    path('product/detail/<int:id>/', get_one_product, name='get_one_product'),

    path('supplier/', ListSupplier.as_view(), name='supplier_list'),
    path('supplier/create/', CreateSupplier.as_view(), name='supplier_create'),
    path('supplier/detail/<int:pk>/', DetailSupplier.as_view(), name='supplier_detail'),
    path('supplier/update/<int:pk>/', UpdateSupplier.as_view(), name='supplier_update'),
    path('supplier/delete/<int:pk>/', DeleteSupplier.as_view(), name='supplier_delete'),

    path('order/<int:pk>/', OrderDetail.as_view(), name='order_detail'),

    path('api/', test_json, name='api_test'),
    path('api/orders/', order_api_list, name='api_order_list'),
    path('api/orders/<int:pk>/', order_api_detail, name='api_order_detail'),

    path('filter/', template_filter_django, name='template_filter_django'),
    path('tags/', template_tag_django, name='template_tag_django'),
]

router = routers.SimpleRouter()
router.register('api/products', ProductViewSet, basename='product')
router.register('api/product_simple', ProductViewSetDif, basename='product_simple')
router.register('api/supplier', SupplierViewSet, basename='supplier')
router.register('api/supply', SupplyViewSet, basename='supply')
router.register('api/category', CategoryViewSet, basename='category')
router.register('api/tag', TagViewSet, basename='tag')
router.register('api/parametr', ParametrViewSet, basename='parametr')
router.register('api/pos_parametr', Pos_parametrViewSet, basename='pos_parametr')
router.register('api/pos_order', Pos_orderViewSet, basename='pos_order')
router.register('api/pos_supply', Pos_supplyViewSet, basename='pos_supply')
router.register('api/warehouse', WarehouseViewSet, basename='warehouse')
router.register('api/inventory', InventoryViewSet, basename='inventory')
router.register('api/review', ReviewViewSet, basename='review')
router.register('api/supplier_admin', SupplierAdminViewSet, basename='supplier_admin')
urlpatterns += router.urls

shop/models.py
from django.db import models
from django.urls import reverse_lazy

from shop.utils import sum_price_count

# Create your models here.
MAX_LENGTH_CHAR = 255


class Supplier(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Название компании')
    agent_firstname = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Фамилия представителя')
    agent_name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Имя представителя')
    agent_surname = models.CharField(max_length=MAX_LENGTH_CHAR, blank=True, null=True,
                                     verbose_name='Отчество представителя')
    agent_telephone = models.CharField(max_length=20, verbose_name='Телефон представителя')
    address = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Адрес')
    is_exists = models.BooleanField(default=True, verbose_name='Логическое удаление')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse_lazy('supplier_detail', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = 'Поставщик'
        verbose_name_plural = 'Поставщики'


class Supply(models.Model):
    data_supply = models.DateTimeField(verbose_name="Дата поставки")
    supplier = models.ForeignKey(Supplier, on_delete=models.PROTECT, verbose_name="Поставщик")

    product = models.ManyToManyField('Product', through='Pos_supply', verbose_name="Товар")

    def __str__(self):
        return f'Номер №{self.pk} - {self.data_supply}'

    class Meta:
        verbose_name = 'Поставка'
        verbose_name_plural = 'Поставки'


class Category(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Название')
    description = models.CharField(max_length=MAX_LENGTH_CHAR, blank=True, null=True, verbose_name='Описание')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Tag(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Название')
    description = models.CharField(max_length=MAX_LENGTH_CHAR, blank=True, null=True, verbose_name='Описание')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'


class Parametr(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Название')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Характеристика'
        verbose_name_plural = 'Характеристики'


class Order(models.Model):
    SHOP = "SH"
    COURIER = "CR"
    PICKUPPOINT = "PP"
    TYPE_DELIVERY = [
        (SHOP, "Магазин"),
        (COURIER, "Курьер"),
        (PICKUPPOINT, "Пункт выдачи"),
    ]
    buyer_name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Имя покупателя')
    buyer_firstname = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Фамилия покупателя')
    buyer_surname = models.CharField(max_length=MAX_LENGTH_CHAR, blank=True, null=True,
                                     verbose_name='Отчество покупателя')
    comment = models.CharField(max_length=MAX_LENGTH_CHAR, blank=True, null=True, verbose_name='Комментарий')
    delivery_address = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Адрес доставки')
    delivery_type = models.CharField(max_length=2, choices=TYPE_DELIVERY, default=SHOP, verbose_name='Способ доставки')
    date_create = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')
    date_finish = models.DateTimeField(null=True, blank=True, verbose_name='Дата завершения заказа')

    product = models.ManyToManyField('Product', through='Pos_order', verbose_name='Товар')

    def __str__(self):
        return f'{self.pk} - ({self.buyer_firstname} {self.buyer_name}) {self.date_create}'

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'


class Product(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Название')
    description = models.CharField(max_length=MAX_LENGTH_CHAR, null=True, blank=True, verbose_name='Описание')
    price = models.FloatField(verbose_name='Цена')
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    update_date = models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')
    photo = models.ImageField(upload_to='image/%Y/%m/%d', null=True, blank=True, verbose_name='Изображение')
    exists = models.BooleanField(default=True, verbose_name='В наличии?')

    category = models.ForeignKey(Category, on_delete=models.PROTECT, verbose_name='Категория')
    tag = models.ManyToManyField(Tag, blank=True, null=True, verbose_name='Тег')

    warehouse = models.ManyToManyField('Warehouse', through='Inventory', verbose_name='Склад')
    parametr = models.ManyToManyField(Parametr, through='Pos_parametr', verbose_name='Характеристики')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class Pos_parametr(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT, verbose_name='Продукт')
    parametr = models.ForeignKey(Parametr, on_delete=models.PROTECT, verbose_name='Характеристика')
    value = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Значение')

    def __str__(self):
        return f'{self.product.name} - {self.value}'

    class Meta:
        verbose_name = 'Характеристика товара'
        verbose_name_plural = 'Характеристики товара'


class Pos_order(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT, verbose_name='Продукт')
    order = models.ForeignKey(Order, on_delete=models.PROTECT, verbose_name='Заказ')
    count = models.PositiveIntegerField(default=1, verbose_name='Количество продукта')
    discount = models.PositiveIntegerField(default=0, verbose_name='Скидка на продукт')

    def __str__(self):
        return f'{self.pk} {self.product.name} {self.order.buyer_firstname} {self.order.buyer_name}'

    def sum_price_count(self):
        return sum_price_count(price=self.product.price, count=self.count, discount=self.discount)

    class Meta:
        verbose_name = 'Позиция заказа'
        verbose_name_plural = 'Позиции заказов'


class Pos_supply(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT, verbose_name='Товар')
    supply = models.ForeignKey(Supply, on_delete=models.PROTECT, verbose_name='Поставка')
    count = models.PositiveIntegerField(verbose_name='Количество товара')

    def __str__(self):
        return f'Номер поставки({self.supply.pk}) - {self.product.name} ({self.count} шт.)'

    class Meta:
        verbose_name = 'Позиция поставки'
        verbose_name_plural = 'Позиции поставок'


class Warehouse(models.Model):
    manager = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Фамилия управляющего')
    location = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Расположение')
    capacity = models.PositiveIntegerField(verbose_name='Вместимость')

    def __str__(self):
        return f'#{self.pk} ({self.location})'

    class Meta:
        verbose_name = 'Склад'
        verbose_name_plural = 'Склады'


class Inventory(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT, verbose_name='Товар')
    warehouse = models.ForeignKey(Warehouse, on_delete=models.PROTECT, verbose_name='Склад')
    quantity = models.PositiveIntegerField(verbose_name='Количество')

    def __str__(self):
        return f'{self.product.name} - {self.warehouse.location}'

    class Meta:
        verbose_name = 'Инвентарь'
        verbose_name_plural = 'Инвентари'


class Review(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Товар')
    user_name = models.CharField(max_length=MAX_LENGTH_CHAR, verbose_name='Имя пользователя')
    rating = models.PositiveIntegerField(verbose_name='Рейтинг')
    comment = models.TextField(verbose_name='Комментарий')

    def __str__(self):
        return f'{self.user_name} - {self.product.name}'

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

shop/forms.py
import re
from django.core.exceptions import ValidationError
from django import forms
from .models import *
class ProductFilterForm(forms.Form):
    name = forms.CharField(
        max_length=150,
        min_length=2,
        strip=True,
        label='Название продукта',
        required=False,
        widget=forms.TextInput(
            attrs={'class':'form-control'}
        )
    )
    min_price = forms.DecimalField(
        label='Минимальная цена',
        required=False,
        min_value=0,
        max_digits=10,
        decimal_places=2,
        step_size=0.01,
        widget=forms.NumberInput(
            attrs={'class': 'form-control'}
        )
    )
    max_price = forms.DecimalField(
        label='Максимальная цена',
        required=False,
        min_value=0,
        max_digits=10,
        decimal_places=2,
        step_size=0.01,
        widget=forms.NumberInput(
            attrs={'class':'form-control'}
        )
    )

class SupplierForm(forms.ModelForm):
    class Meta:
        model = Supplier
        fields = (
            'name',
            'agent_firstname',
            'agent_name',
            'agent_surname',
            'agent_telephone',
            'address',
            'is_exists'
        )

shop/templates/shop/product/catalog.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Все товары</title>
    <link rel="stylesheet" href="{% static 'shop/css/bootstrap.css' %}">
</head>
<body>
<table class="table">
    <tbody class="table-primary">
    {% for product in product_list %}
        <tr>
            <td>
                <div class="row">
                    <div class="col col-3">
                        {{ product.name }} - {{ product.price }}
                    </div>
                    <div class="col col-3">
                        {{ product.description }}
                    </div>
                    <div class="col col-6">
                        Заказы:
                        {% for ord in product.pos_order_set.all %}
                            <ul>
                                <li>
                                    #{{ ord.order.pk }} {{ ord.order.date_create }} - {{ ord.order.buyer_firstname }}
                                    ({{ ord.count }} шт.)
                                </li>
                            </ul>
                        {% empty %}
                            <p>
                                Никто еще не совершил заказы
                            </p>
                        {% endfor %}
                    </div>
                </div>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
</body>
</html>

shop/templates/shop/product/catalog_with_filter.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Фильтр на товары</title>
    <link rel="stylesheet" href="{% static 'shop/css/bootstrap.css'%}">
    <style>
        .card-img-top {
            width: 100%;
            height: 60vh;
            object-fit: cover;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="container">
            <div class="row">
                <div class="col-8">
                    <ul>
                        {% if request.user.is_anonymous %}
                            <li><a class="btn btn-outline-primary" href="{% url 'log in' %}">Авторизация</a></li>
                            <li><a class="btn btn-outline-success" href="{% url 'regis' %}">Регистрация</a></li>
                        {% else %}
                            <li><a class="btn btn-outline-danger" href="{% url 'log out' %}">Выход из профиля</a></li>
                        {% endif %}
                    </ul>
                </div>
                <div class="col-4">
                    Здравствуйте, {{ user }}
                </div>
            </div>
        </div>
        <h1 style="display: flex; justify-content: center;">Каталог платьев</h1>
     <form>
        {{ form.as_div }}
        <button type="submit" class="btn btn-outline-dark">Применить фильтр</button>
    </form>
    <div class="container">
        <div class="row">
            {% for product in list_product %}
                <div class="col-4">
                    <div class="card" style="width: 18rem;">
                        {% if product.photo %}
                            <img src="{{ product.photo.url }}" class="card-img-top" alt="...">
                        {% else %}
                            <img src="{% static 'shop/image/no_photo.jpg' %}" class="card-img-top" alt="...">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ product.name }}</h5>
                            <h6 class="card-subtitle mb-2 text-body-secondary">
                                Категория: {{ product.category.name }}
                            </h6>
                            <h6 class="card-subtitle mb-2 text-body-secondary">
                                Теги: {% for tag in product.tag.all %}
                                    {{ tag.nane }}
                                    {% endfor %}
                            </h6>
                            <p class="card-text">{{ product.description }}</p>
                            <p class="card-text">Цена:{{ product.price }} руб.</p>
                            {% if request.user.is_authenticated %}
                                <a href="{% url 'get_one_product' product.pk %}" class="btn btn-success">Подробнее...</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
 </div>
</body>
</html>

shop/templates/shop/product/filter_product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

shop/templates/shop/product/one_product.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'shop/css/bootstrap.css' %}">
</head>
<body>
<h1 style="display: flex; justify-content: center; color: sandybrown">Подробнее о {{ product.name }}</h1>
<div class="p-3">
    <table class="table table-bordered table-dark">
        <thead class="table-primary">
        <tr>
            <th>Название</th>
            <th>Описание</th>
            <th>Стоимость</th>
            <th>В наличии на складе</th>
            <th>Теги</th>
            <th>Картинка</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>{{ product.name }}</td>
            <td>
                {% if product.description %}
                    {{ product.description }}
                {% else %}
                    Описание отсутствует
                {% endif %}
            </td>
            <td>{{ product.price }}</td>
            <td>
                <ul>
                    {% for warehouse in product.warehouse.all %}
                        <li>{{ warehouse.location }}</li>
                    {% empty %}
                        <li>Нет в наличии на складах</li>
                    {% endfor %}
                </ul>
            </td>
            <td>
                <ul>
                    {% for tag in product.tag.all %}
                        <li>{{ tag.name }}</li>
                    {% empty %}
                        <li>Нет актуальных тегов</li>
                    {% endfor %}
                </ul>
            </td>
            <td>
                {% if product.photo %}
                    <img src="{{ product.photo.url }}" alt="..."
                         style="max-height: 400px; max-width: 400px; object-fit: contain; border-radius: 20px">
                {% else %}
                    <img src="{% static 'shop/image/no_photo.jpg' %}" alt="...">
                {% endif %}
            </td>
        </tr>
        </tbody>
    </table>
    <form method="post" action="{% url 'basket_add' product.pk %}" class="my-2">
        {% csrf_token %}
        {{ form_basket }}
        <button type="submit" class="btn btn-outline-success my-2">Добавить в корзину</button>
    </form>
    <a href="{% url 'product_list_filter' %}" class="btn btn-outline-dark">Назад к каталогу</a>
</div>
</body>
</html>